apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    type: http-service
spec:
  selector:
    apps: http-ser
  type: NodePort
  ports:
    - nodePort: 30000
      port: 80
      targetPort: 80
